use soroban_sdk::{contractimpl, Address, Env};

use crate::error::RentalError;
use crate::storage;
// RentalEscrowArgs and RentalEscrowClient are generated by the `#[contract]`
// macro at the crate root; `#[contractimpl]` blocks in other modules must
// import them to be in scope.
use crate::{RentalEscrow, RentalEscrowArgs, RentalEscrowClient};

#[contractimpl]
impl RentalEscrow {
    /// One-time contract setup. Auth: `admin`. Stores the platform admin,
    /// the dispute arbiter and the SEP-41 token used for every fund
    /// movement. Real-world action: platform bootstrap before any
    /// agreement can be created. Fails with `AlreadyInitialized` if
    /// called a second time.
    pub fn initialize(
        env: &Env,
        admin: Address,
        arbiter: Address,
        token: Address,
    ) -> Result<(), RentalError> {
        admin.require_auth();
        if storage::is_initialized(env) {
            return Err(RentalError::AlreadyInitialized);
        }
        storage::write_initialized(env, &admin, &arbiter, &token);
        Ok(())
    }
}
