use soroban_sdk::token::TokenClient;
use soroban_sdk::{contractimpl, Address, Env, String};

use crate::error::RentalError;
use crate::storage;
use crate::types::{AgreementStatus, RentalAgreement};
// RentalEscrowArgs and RentalEscrowClient are generated by the `#[contract]`
// macro at the crate root; `#[contractimpl]` blocks in other modules must
// import them to be in scope.
use crate::{RentalEscrow, RentalEscrowArgs, RentalEscrowClient};

#[contractimpl]
impl RentalEscrow {
    /// One-time contract setup. Auth: `admin`. Stores the platform admin,
    /// the dispute arbiter and the SEP-41 token used for every fund
    /// movement. Real-world action: platform bootstrap before any
    /// agreement can be created. Fails with `AlreadyInitialized` if
    /// called a second time.
    pub fn initialize(
        env: &Env,
        admin: Address,
        arbiter: Address,
        token: Address,
    ) -> Result<(), RentalError> {
        admin.require_auth();
        if storage::is_initialized(env) {
            return Err(RentalError::AlreadyInitialized);
        }
        storage::write_initialized(env, &admin, &arbiter, &token);
        Ok(())
    }

    /// Creates a new rental agreement. Auth: `owner`. Validates that the
    /// rental period is well-formed and both amounts are positive, then
    /// stores the agreement as `Created` and returns its id. Real-world
    /// action: the owner accepting a rental request from a renter for a
    /// specific item over a specific period.
    pub fn create_agreement(
        env: &Env,
        owner: Address,
        renter: Address,
        item_ref: String,
        rental_amount: i128,
        deposit_amount: i128,
        start_time: u64,
        end_time: u64,
        claim_window_secs: u64,
    ) -> Result<u64, RentalError> {
        owner.require_auth();
        if rental_amount <= 0 || deposit_amount <= 0 {
            return Err(RentalError::InvalidAmount);
        }
        if end_time <= start_time {
            return Err(RentalError::InvalidTimeRange);
        }
        let id = storage::read_next_id(env);
        storage::write_next_id(env, id.checked_add(1).ok_or(RentalError::Overflow)?);
        let agreement = RentalAgreement {
            id,
            owner: owner.clone(),
            renter: renter.clone(),
            item_ref,
            rental_amount,
            deposit_amount,
            start_time,
            end_time,
            claim_window_secs,
            status: AgreementStatus::Created,
            created_at: env.ledger().timestamp(),
        };
        storage::write_agreement(env, &agreement);
        Ok(id)
    }

    /// Funds a created agreement. Auth: `renter`. Transfers
    /// `rental_amount + deposit_amount` from the renter into the escrow
    /// contract through the SEP-41 token. Real-world action: the renter
    /// paying the rental fee and locking the security deposit before
    /// handover. Failing to fund keeps the agreement in `Created`;
    /// a failed token transfer aborts the transaction at the host level
    /// and reverts all state, which is the correct escrow behavior.
    pub fn fund_agreement(env: &Env, renter: Address, id: u64) -> Result<(), RentalError> {
        renter.require_auth();
        let mut agreement = storage::read_agreement(env, id)?;
        // The caller must be the agreement's renter: require_auth proves the
        // passed address signed, this check proves it is the right address.
        if agreement.renter != renter {
            return Err(RentalError::Unauthorized);
        }
        match agreement.status {
            AgreementStatus::Created => {}
            AgreementStatus::Funded => return Err(RentalError::AlreadyFunded),
            _ => return Err(RentalError::InvalidStatus),
        }
        let total = agreement
            .rental_amount
            .checked_add(agreement.deposit_amount)
            .ok_or(RentalError::Overflow)?;
        let token = TokenClient::new(env, &storage::read_token(env)?);
        token.transfer(&renter, &env.current_contract_address(), &total);
        agreement.status = AgreementStatus::Funded;
        storage::write_agreement(env, &agreement);
        Ok(())
    }
}
