use soroban_sdk::token::TokenClient;
use soroban_sdk::{contractimpl, Address, Env, String};

use crate::error::RentalError;
use crate::events;
use crate::storage;
use crate::types::{AgreementStatus, RentalAgreement};
// RentalEscrowArgs and RentalEscrowClient are generated by the `#[contract]`
// macro at the crate root; `#[contractimpl]` blocks in other modules must
// import them to be in scope.
use crate::{RentalEscrow, RentalEscrowArgs, RentalEscrowClient};

#[contractimpl]
impl RentalEscrow {
    /// One-time contract setup. Auth: `admin`. Stores the platform admin,
    /// the dispute arbiter and the SEP-41 token used for every fund
    /// movement. Real-world action: platform bootstrap before any
    /// agreement can be created. Fails with `AlreadyInitialized` if
    /// called a second time.
    pub fn initialize(
        env: &Env,
        admin: Address,
        arbiter: Address,
        token: Address,
    ) -> Result<(), RentalError> {
        admin.require_auth();
        if storage::is_initialized(env) {
            return Err(RentalError::AlreadyInitialized);
        }
        storage::write_initialized(env, &admin, &arbiter, &token);
        Ok(())
    }

    /// Creates a new rental agreement. Auth: `owner`. Validates that the
    /// rental period is well-formed and both amounts are positive, then
    /// stores the agreement as `Created` and returns its id. Real-world
    /// action: the owner accepting a rental request from a renter for a
    /// specific item over a specific period.
    pub fn create_agreement(
        env: &Env,
        owner: Address,
        renter: Address,
        item_ref: String,
        rental_amount: i128,
        deposit_amount: i128,
        start_time: u64,
        end_time: u64,
        claim_window_secs: u64,
    ) -> Result<u64, RentalError> {
        owner.require_auth();
        if owner == renter {
            return Err(RentalError::SameOwnerAndRenter);
        }
        if rental_amount <= 0 || deposit_amount <= 0 {
            return Err(RentalError::InvalidAmount);
        }
        if end_time <= start_time {
            return Err(RentalError::InvalidTimeRange);
        }
        let id = storage::read_next_id(env);
        storage::write_next_id(env, id.checked_add(1).ok_or(RentalError::Overflow)?);
        let agreement = RentalAgreement {
            id,
            owner: owner.clone(),
            renter: renter.clone(),
            item_ref,
            rental_amount,
            deposit_amount,
            start_time,
            end_time,
            claim_window_secs,
            status: AgreementStatus::Created,
            created_at: env.ledger().timestamp(),
        };
        storage::write_agreement(env, &agreement);
        events::agreement_created(env, &agreement);
        Ok(id)
    }

    /// Funds a created agreement. Auth: `renter`. Transfers
    /// `rental_amount + deposit_amount` from the renter into the escrow
    /// contract through the SEP-41 token. Real-world action: the renter
    /// paying the rental fee and locking the security deposit before
    /// handover. Failing to fund keeps the agreement in `Created`;
    /// a failed token transfer aborts the transaction at the host level
    /// and reverts all state, which is the correct escrow behavior.
    pub fn fund_agreement(env: &Env, renter: Address, id: u64) -> Result<(), RentalError> {
        renter.require_auth();
        let mut agreement = storage::read_agreement(env, id)?;
        // The caller must be the agreement's renter: require_auth proves the
        // passed address signed, this check proves it is the right address.
        if agreement.renter != renter {
            return Err(RentalError::Unauthorized);
        }
        match agreement.status {
            AgreementStatus::Created => {}
            AgreementStatus::Funded => return Err(RentalError::AlreadyFunded),
            _ => return Err(RentalError::InvalidStatus),
        }
        let total = agreement
            .rental_amount
            .checked_add(agreement.deposit_amount)
            .ok_or(RentalError::Overflow)?;
        let token = TokenClient::new(env, &storage::read_token(env)?);
        token.transfer(&renter, &env.current_contract_address(), &total);
        agreement.status = AgreementStatus::Funded;
        storage::write_agreement(env, &agreement);
        events::agreement_funded(env, id, total);
        Ok(())
    }

    /// Confirms physical handover of the item. Auth: `owner`. Requires
    /// status `Funded`; sets status `Active`. Real-world action: the
    /// owner handing the item to the renter and confirming it in the app.
    pub fn start_rental(env: &Env, owner: Address, id: u64) -> Result<(), RentalError> {
        owner.require_auth();
        let mut agreement = storage::read_agreement(env, id)?;
        // require_auth proves the caller signed; this proves they are the
        // agreement's owner.
        if agreement.owner != owner {
            return Err(RentalError::Unauthorized);
        }
        if agreement.status != AgreementStatus::Funded {
            return Err(RentalError::InvalidStatus);
        }
        agreement.status = AgreementStatus::Active;
        storage::write_agreement(env, &agreement);
        events::rental_started(env, id);
        Ok(())
    }

    /// Releases escrowed funds after a clean rental. Auth: none. This is
    /// permissionless and time-gated: anyone may call it once the claim
    /// window has passed with no claim raised (`now > end_time +
    /// claim_window_secs`). Returns the deposit to the renter and the
    /// rental fee to the owner, then marks the agreement `Completed`.
    /// Real-world action: automatic settlement of an undisputed rental.
    pub fn release_funds(env: &Env, id: u64) -> Result<(), RentalError> {
        let mut agreement = storage::read_agreement(env, id)?;
        if agreement.status != AgreementStatus::Active {
            return Err(RentalError::InvalidStatus);
        }
        let claim_deadline = agreement
            .end_time
            .checked_add(agreement.claim_window_secs)
            .ok_or(RentalError::Overflow)?;
        if env.ledger().timestamp() <= claim_deadline {
            return Err(RentalError::ClaimWindowActive);
        }
        let token = TokenClient::new(env, &storage::read_token(env)?);
        let contract = env.current_contract_address();
        token.transfer(&contract, &agreement.renter, &agreement.deposit_amount);
        token.transfer(&contract, &agreement.owner, &agreement.rental_amount);
        agreement.status = AgreementStatus::Completed;
        storage::write_agreement(env, &agreement);
        events::funds_released(env, id);
        Ok(())
    }

    /// Cancels an agreement before it is funded. Auth: `caller` must be
    /// the stored `owner` or `renter`. Requires status `Created` only;
    /// sets status `Cancelled`. Real-world action: either party backing
    /// out before any money moves. Known scope limit, not a bug: funded
    /// agreements cannot be cancelled in v1, there is no mutual-consent
    /// cancellation path.
    pub fn cancel_agreement(env: &Env, caller: Address, id: u64) -> Result<(), RentalError> {
        caller.require_auth();
        let mut agreement = storage::read_agreement(env, id)?;
        if caller != agreement.owner && caller != agreement.renter {
            return Err(RentalError::Unauthorized);
        }
        if agreement.status != AgreementStatus::Created {
            return Err(RentalError::InvalidStatus);
        }
        agreement.status = AgreementStatus::Cancelled;
        storage::write_agreement(env, &agreement);
        events::agreement_cancelled(env, id);
        Ok(())
    }
}
